
version: '3.8'

services:
  web:
    build:
      context: ./gpds-ui/
      dockerfile: Dockerfile
    ports:
      - "8081:80" 
    volumes:
      - ./gpds-ui/nginx.conf:/etc/nginx/nginx.conf # 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
